language: python
python:
  - 2.7
  - 3.2
addons:
  postgresql: "9.3"
env:
  matrix:
    - DJANGO_SETTINGS_MODULE=api.settings.production DATABASE_URL=postgres://postgres:@localhost:5432/stagecraft
  global:
    # Contains GH_TOKEN=<secret token> for release tagging
    secure: "Vb04vYzCM9PU/TWJ5Hi+kd1/txtRylAdYbfLpjwVsHhnMLXrJIHrMwx6vVHg24aZM64ODufvoQyVLlp3FBGNqgSycZBM3jDxtqqUhQEe39dAvQnPjjR3QH+fjoAUaEpmUKLl/Zp6noUsIBjgry/Mviq9HkTR4UhjxZz+Xks+lx4="
matrix:
  fast_finish: true
  allow_failures:
    - python: 3.2
install:
  -  pip install -r requirements_for_travis.txt
before_script:
  - psql -c 'create database stagecraft;' -U postgres
script:
  - ./run_tests.sh
notifications:
  email: false
