language: python
python:
  - 2.7
  - 3.2
matrix:
  fast_finish: true
  allow_failures:
    - python: 3.2
install: 
  -  pip install -r requirements_for_travis.txt
script:
  - ./run_tests.sh
notifications:
  email: false
