language: python
python:
  - 2.7
  - 3.2
addons:
  postgresql: "9.3"
env:
  matrix:
    - DJANGO_SETTINGS_MODULE=api.settings.production DATABASE_URL=postgres://postgres:@localhost:5432/stagecraft
matrix:
  fast_finish: true
  allow_failures:
    - python: 3.2
install:
  -  pip install -r requirements_for_travis.txt
before_script:
  - psql -c 'create database stagecraft;' -U postgres
script:
  - ./run_tests.sh
notifications:
  email: false
